spring:
  application:
    name: shop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
