spring:
  application:
    name: shop

  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: mshop_admin
    password: 1234

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

file:
  upload:
    itemImgLocation: C:/shop/item
    uploadPath: file:///C:/shop/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml